# Generated by Django 5.1.4 on 2024-12-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['position'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position'], 'verbose_name': 'Вопрос для голосования', 'verbose_name_plural': 'Вопросы для голосования'},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='polls',
        ),
        migrations.AddField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(to='polls.question', verbose_name='Вопросы'),
        ),
    ]
