# Generated by Django 5.1.4 on 2024-12-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_choice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Один вариант ответа', 'Один вариант ответа'), ('Несколько вариантов ответа', 'Несколько вариантов ответа')], default=('Один вариант ответа', 'Один вариант ответа'), max_length=30),
        ),
    ]
