# Generated by Django 5.1.4 on 2025-01-04 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_choice_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.poll'),
            preserve_default=False,
        ),
    ]
