# Generated by Django 5.1.4 on 2024-12-11 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_vote_poll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос для голосования',
                'verbose_name_plural': 'Вопросы для голосования',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['name'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['theme'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='name',
        ),
        migrations.AddField(
            model_name='poll',
            name='theme',
            field=models.CharField(default='Вопрос', max_length=1024, verbose_name='Тема опроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Вариант ответа'),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='polls',
            field=models.ManyToManyField(to='polls.question', verbose_name='Опросы'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Проголосовавшие'),
        ),
    ]
