# Generated by Django 5.1.4 on 2024-12-10 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_vote_poll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Проголосовавшие'),
        ),
    ]
