# Generated by Django 5.1.4 on 2024-12-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_alter_choice_options_alter_poll_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция варианта ответа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция вопроса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Один', 'Один вариант ответа'), ('Несколько', 'Несколько вариантов ответа')], default=('Один', 'Один вариант ответа'), max_length=10),
        ),
    ]
